### ISSUE TITLE
Ability to create metric destinations

### ISSUE THREAD

**Issue by charles-bluett** [BlueMedoraPublic/terraform-provider-bindplane#13]
It would be nice to be able to create a metric destination in the terraform.

**Comment by jsirianni** [comment]
Hi @charles-bluett, I will be following up on this. I will post any updates here.

**Comment by jsirianni** [comment]
Hi @charles-bluett. Back when this issue was posted, support for Destinations was not available. After internal discussion, it has been decided that adding this ability will not make it onto the road map. Generally, customers have one destination that is created during account setup.

Feel free to re-open this issue if you have many destinations that need to be managed.
