### ISSUE TITLE
MongoDB source always gets replaced on apply

### ISSUE THREAD

**Issue by jduplessis** [BlueMedoraPublic/terraform-provider-bindplane#16]
First of all, I'm excited to be able to config BindPlane with Terraform!

I found a potential bug, but I might also be missing something small.

My Terraform setup looks like this:
![image](https://user-images.githubusercontent.com/2579639/103262062-76b97400-49ac-11eb-9ca6-d067b676cb03.png)

Every `terraform apply` (and `terraform plan`) produces this even after the `terraform apply` has been executed:
![image](https://user-images.githubusercontent.com/2579639/103262212-e596cd00-49ac-11eb-830e-2d2334cd9977.png)

I work with Terraform a lot, but I've never seen `# forces replacement` with green `+` symbols only.

**Comment by jsirianni** [comment]
Hi @jduplessis, thank you submitting this issue. Can you provide the platform and the output of `terraform version`? 

I will try to replicate this issue and provide a solution. 

Thanks!

**Comment by jduplessis** [comment]
`OS`: Windows 10

`Terraform`:  ![image](https://user-images.githubusercontent.com/2579639/103284043-d468b300-49e2-11eb-8cb3-851449150048.png)

**Comment by jsirianni** [comment]
@jduplessis I believe there are two issues:

1. `authentication` is not a parameter, therefore when Terraform queries the API it thinks it needs to replace the source because that parameter is missing.

2. The parameter order matters. It should look like this:
```
...
    configuration = <<CONFIGURATION
{
  "connection_timeout": 3,
  "host": "<redacted>",
  "port": 27017,
  "ssl": "Verify"
}
CONFIGURATION
```

Number 2 is silly, parameter order should not matter. I have a new issue for tracking this specific bug: https://github.com/BlueMedoraPublic/terraform-provider-bindplane/issues/18

Feel free to subscribe on the new issue, in order to receive notifications related to its status. For now, please reference the output of [bpcli source type template](https://github.com/BlueMedoraPublic/bpcli) for parameter order.
```
❯ bpcli source type template --id mongo_mongodb --json
{
  "name": "YOUR_MONGO_MONGODB_NAME",
  "source_type": "mongo_mongodb",
  "collector_id": "YOUR_COLLECTOR_ID",
  "collection_interval": 60,
  "credentials": {
    "credentials": "YOUR_CREDENTIALS_ID"
  },
  "configuration": {
    "connection_timeout": 3,
    "host": "YOUR_HOST",
    "port": 27017,
    "ssl": "No Verify"
  }
}
```

**Comment by jduplessis** [comment]
Thanks @jsirianni I'm sure this will resolve the the problem I experienced.
